import type { Metadata } from "next";
import { Open_Sans, Playfair_Display, Source_Serif_4, Spicy_Rice } from "next/font/google";
import "./globals.css";

const spicyRice = Spicy_Rice({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-spicy'
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair'
});

const sourceSerif = Source_Serif_4({
  subsets: ['latin'],
  variable: '--font-source'
});

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${spicyRice.variable} ${playfair.variable} ${sourceSerif.variable} ${openSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}